#!/usr/bin/env node

// module.exports = function random(max) {
//   return Math.floor(Math.random() * (max + 1))
// }

const input = Number(process.argv[2])
const max = Number.isNaN(input) ? undefined : input
const result = random(max)
console.log(result)

function random(max = 10) {
  return Math.floor(Math.random() * (max + 1))
}
